name: food_delivery_app
description: A Flutter food delivery application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # State Management
  provider: ^6.1.0

  # Network
  dio: ^5.4.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # JSON Serialization
  json_annotation: ^4.8.1

  # Utils
  intl: ^0.18.1
  logger: ^2.0.2

  # Image & Cache
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4

  # UI Components
  shimmer: ^3.0.0

  # Notifications
  flutter_local_notifications: ^16.3.0

  # Permissions
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
